### ISSUE TITLE
Connect `TaskListViewModel` to in-memory database

### ISSUE THREAD

**Issue by WizardPlatypus** [Nemesnyky/studennyk#39]
Make sure database is populated with random data, but only once during the app's lifetime.

To achieve so, add SQLiteRepository as singleton dependency to the application.

**Comment by WizardPlatypus** [comment]
Here are a few useful links i found:

- an article explaining different dependency injection techniques: https://blog.ewers-peters.de/are-you-using-dependency-injection-in-your-net-maui-app-yet
- a GitHub repository containing a bunch of examples of MAUI projects: https://github.com/VladislavAntonyuk/MauiSamples/tree/main

**Comment by Ura3535** [comment]
I was having trouble implementing a singleton dependency for ContentView (Agenda), but came across a discussion of this problem: https://github.com/dotnet/maui/discussions/8363
For now, we'll use AppServiceProvider class: https://github.com/davidortinau/WeatherTwentyOne/blob/main/src/WeatherTwentyOne/Services/ServiceExtensions.cs
